[package]
name = "onvif-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
once_cell = "1.21.3"
ratatui = "0.29.0"
regex = "1.11.1"
reqwest = "0.12.23"
tui-textarea = "0.7.0"
xml = "0.8.20"
